name: Trigger auto deployment for container-app-xfhouuqjbkw4i

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/container-app-xfhouuqjbkw4i-AutoDeployTrigger-e8874890-c387-49ea-af30-e9fcc9a3da7b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPXFHOUUQJBKW4I_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPXFHOUUQJBKW4I_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPXFHOUUQJBKW4I_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryxfhouuqjbkw4i.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPXFHOUUQJBKW4I_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPXFHOUUQJBKW4I_REGISTRY_PASSWORD }}
          containerAppName: container-app-xfhouuqjbkw4i
          resourceGroup: githubactiontestfunctionapppythonabfb
          imageToBuild: containerregistryxfhouuqjbkw4i.azurecr.io/container-app-xfhouuqjbkw4i:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


